import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "@/components/provider/theme-provider";
import ReactQueryProvider from "@/components/provider/query-provider";
import AppHeader from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Madia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextThemesProvider attribute="class" defaultTheme="system">
            {/* <AppHeader /> */}
            {children}
          </NextThemesProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
